name: "OpenConnect client"
description: "OpenConnect client addon"
version: "1.0.0"
slug: "openconnect_client"
startup: "before"
boot: "auto"
host_network: true
privileged: 
  - NET_ADMIN
init: false
options:
  server_url: "https://example.com:8443"
  username: "beer"
  password: "123456"
schema:
  server_url: url
  username: str
  password: str
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386